use serde::{Serialize, Deserialize};
use serde_json::json;
use crate::storage::keychain::get_key;
use crate::storage::sqlite::get_setting_internal;

/// Read the sidecar authentication token from the local settings database.
/// This token is generated by the Python sidecar on startup and stored here by the Rust orchestrator.
fn get_sidecar_token() -> Option<String> {
    get_setting_internal("sidecar_token")
        .unwrap_or(None)
}

/// Apply the sidecar token header for self-hosted requests.
fn apply_sidecar_auth(builder: reqwest::RequestBuilder, mem0_type: &str) -> reqwest::RequestBuilder {
    if mem0_type != "cloud" {
        if let Some(token) = get_sidecar_token() {
            return builder.header("X-Sidecar-Token", token);
        }
    }
    builder
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Mem0SearchResponse {
    pub id: String,
    pub memory: String,
    pub user_id: Option<String>,
}

/// Fetch semantically relevant memories from Mem0 using the configured mode and keys.
pub async fn fetch_mem0_memories(instruction: &str, user_id: &str) -> Option<String> {
    // 1. Load configuration from SQLite
    let mem0_type = get_setting_internal("mem0_type")
        .unwrap_or(None)
        .unwrap_or_else(|| "cloud".to_string());
    
    let mem0_url = get_setting_internal("mem0_url")
        .unwrap_or(None)
        .unwrap_or_else(|| "https://api.mem0.ai".to_string());

    // 2. Fetch API Key from DPAPI Keychain (optional for self-hosted)
    let api_key = get_key("mem0").ok().flatten();
    
    if api_key.is_none() && mem0_type == "cloud" {
        return None; // Cloud mode requires a key
    }

    let client = reqwest::Client::new();
    let url = if mem0_type == "cloud" {
        format!("{}/v3/memories/search/", mem0_url.trim_end_matches('/'))
    } else {
        format!("{}/search", mem0_url.trim_end_matches('/'))
    };

    let payload = if mem0_type == "cloud" {
        json!({
            "query": instruction,
            "filters": {
                "user_id": user_id
            },
            "top_k": 5
        })
    } else {
        json!({
            "query": instruction,
            "user_id": user_id,
            "limit": 5
        })
    };

    let mut req = client.post(&url).header("Content-Type", "application/json");
    req = apply_sidecar_auth(req, &mem0_type);
    if let Some(ref key) = api_key {
        if !key.is_empty() {
            req = req.header("Authorization", format!("Token {}", key));
        }
    }

    let response = match req.json(&payload).send().await {
        Ok(res) => res,
        Err(_) => return None,
    };

    if !response.status().is_success() {
        return None;
    }

    let search_results: Vec<Mem0SearchResponse> = match response.json().await {
        Ok(res) => res,
        Err(_) => return None,
    };

    if search_results.is_empty() {
        return None;
    }

    // Combine memories into a single context string
    let mut combined = String::from("Here are relevant facts from past tasks:\n");
    for res in search_results {
        combined.push_str(&format!("- {}\n", res.memory));
    }
    Some(combined)
}

/// Add task and outcome as conversation turns to Mem0 vector engine.
pub async fn add_mem0_memory(instruction: &str, outcome: &str, user_id: &str) -> Result<(), String> {
    let mem0_type = get_setting_internal("mem0_type")
        .unwrap_or(None)
        .unwrap_or_else(|| "cloud".to_string());
    
    let mem0_url = get_setting_internal("mem0_url")
        .unwrap_or(None)
        .unwrap_or_else(|| "https://api.mem0.ai".to_string());

    let api_key = get_key("mem0").ok().flatten();
    
    if api_key.is_none() && mem0_type == "cloud" {
        return Ok(()); // Cloud mode requires a key
    }

    let client = reqwest::Client::new();
    let url = if mem0_type == "cloud" {
        format!("{}/v3/memories/add/", mem0_url.trim_end_matches('/'))
    } else {
        format!("{}/memories", mem0_url.trim_end_matches('/'))
    };

    let payload = json!({
        "user_id": user_id,
        "messages": [
            {
                "role": "user",
                "content": instruction
            },
            {
                "role": "assistant",
                "content": outcome
            }
        ]
    });

    let mut req = client.post(&url).header("Content-Type", "application/json");
    req = apply_sidecar_auth(req, &mem0_type);
    if let Some(ref key) = api_key {
        if !key.is_empty() {
            req = req.header("Authorization", format!("Token {}", key));
        }
    }

    let response = req.json(&payload)
        .send()
        .await
        .map_err(|e| e.to_string())?;

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("Mem0 API Error: {}", err_text));
    }

    // Mirror memory to Supabase DB and backup Chroma DB zip to Storage
    let user_id_clone = user_id.to_string();
    let content_clone = format!("Instruction: {} | Outcome: {}", instruction, outcome);
    tauri::async_runtime::spawn(async move {
        let _ = crate::storage::supabase::insert_memory_to_supabase(&user_id_clone, "episodic", &content_clone).await;
        crate::storage::supabase::sync_all_to_cloud_async(None, None).await;
    });

    Ok(())
}

/// Retrieve all cognitive memories currently registered for a specific user.
#[tauri::command]
pub async fn get_all_memories(user_id: String) -> Result<Vec<Mem0SearchResponse>, String> {
    let mem0_type = get_setting_internal("mem0_type")
        .unwrap_or(None)
        .unwrap_or_else(|| "cloud".to_string());
    
    let mem0_url = get_setting_internal("mem0_url")
        .unwrap_or(None)
        .unwrap_or_else(|| "https://api.mem0.ai".to_string());

    let api_key = get_key("mem0").ok().flatten();

    if api_key.is_none() && mem0_type == "cloud" {
        return Ok(Vec::new());
    }

    let client = reqwest::Client::new();
    let response = if mem0_type == "cloud" {
        let url = format!("{}/v3/memories/", mem0_url.trim_end_matches('/'));
        let payload = json!({
            "filters": {
                "user_id": user_id
            }
        });
        let mut req = client.post(&url).header("Content-Type", "application/json");
        req = apply_sidecar_auth(req, &mem0_type);
        if let Some(ref key) = api_key {
            if !key.is_empty() {
                req = req.header("Authorization", format!("Token {}", key));
            }
        }
        req.json(&payload).send().await.map_err(|e| e.to_string())?
    } else {
        let url = format!("{}/memories?user_id={}", mem0_url.trim_end_matches('/'), user_id);
        let mut req = client.get(&url);
        req = apply_sidecar_auth(req, &mem0_type);
        if let Some(ref key) = api_key {
            if !key.is_empty() {
                req = req.header("Authorization", format!("Token {}", key));
            }
        }
        req.send().await.map_err(|e| e.to_string())?
    };

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("Mem0 API Error: {}", err_text));
    }

    let results: Vec<Mem0SearchResponse> = response.json().await.map_err(|e| e.to_string())?;
    Ok(results)
}

/// Purge a specific memory record by its unique ID.
#[tauri::command]
pub async fn delete_memory_item(memory_id: String) -> Result<(), String> {
    let mem0_type = get_setting_internal("mem0_type")
        .unwrap_or(None)
        .unwrap_or_else(|| "cloud".to_string());
    
    let mem0_url = get_setting_internal("mem0_url")
        .unwrap_or(None)
        .unwrap_or_else(|| "https://api.mem0.ai".to_string());

    let api_key = get_key("mem0").ok().flatten();

    let client = reqwest::Client::new();
    let url = if mem0_type == "cloud" {
        format!("{}/v3/memories/{}/", mem0_url.trim_end_matches('/'), memory_id)
    } else {
        format!("{}/memories/{}", mem0_url.trim_end_matches('/'), memory_id)
    };

    let mut req = client.delete(&url);
    req = apply_sidecar_auth(req, &mem0_type);
    if let Some(ref key) = api_key {
        if !key.is_empty() {
            req = req.header("Authorization", format!("Token {}", key));
        }
    }

    let response = req.send().await.map_err(|e| e.to_string())?;

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("Mem0 API Error: {}", err_text));
    }

    // Trigger storage sync to update chroma_db.zip after deletion
    tauri::async_runtime::spawn(async move {
        crate::storage::supabase::sync_all_to_cloud_async(None, None).await;
    });

    Ok(())
}

/// Search semantic memories for a user matching a query.
#[tauri::command]
pub async fn search_memory_items(query: String, user_id: String) -> Result<Vec<Mem0SearchResponse>, String> {
    let mem0_type = get_setting_internal("mem0_type")
        .unwrap_or(None)
        .unwrap_or_else(|| "cloud".to_string());
    
    let mem0_url = get_setting_internal("mem0_url")
        .unwrap_or(None)
        .unwrap_or_else(|| "https://api.mem0.ai".to_string());

    let api_key = get_key("mem0").ok().flatten();

    if api_key.is_none() && mem0_type == "cloud" {
        return Ok(Vec::new());
    }

    let client = reqwest::Client::new();
    let url = if mem0_type == "cloud" {
        format!("{}/v3/memories/search/", mem0_url.trim_end_matches('/'))
    } else {
        format!("{}/search", mem0_url.trim_end_matches('/'))
    };

    let payload = if mem0_type == "cloud" {
        json!({
            "query": query,
            "filters": {
                "user_id": user_id
            },
            "top_k": 10
        })
    } else {
        json!({
            "query": query,
            "user_id": user_id,
            "limit": 10
        })
    };

    let mut req = client.post(&url).header("Content-Type", "application/json");
    req = apply_sidecar_auth(req, &mem0_type);
    if let Some(ref key) = api_key {
        if !key.is_empty() {
            req = req.header("Authorization", format!("Token {}", key));
        }
    }

    let response = req.json(&payload).send().await.map_err(|e| e.to_string())?;

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("Mem0 API Error: {}", err_text));
    }

    let results: Vec<Mem0SearchResponse> = response.json().await.map_err(|e| e.to_string())?;
    Ok(results)
}

/// Allows direct manual memory injection from the Memory dashboard tab.
#[tauri::command]
pub async fn add_custom_memory_item(memory: String, user_id: String) -> Result<(), String> {
    let mem0_type = get_setting_internal("mem0_type")
        .unwrap_or(None)
        .unwrap_or_else(|| "cloud".to_string());
    
    let mem0_url = get_setting_internal("mem0_url")
        .unwrap_or(None)
        .unwrap_or_else(|| "https://api.mem0.ai".to_string());

    let api_key = get_key("mem0").ok().flatten();

    if api_key.is_none() && mem0_type == "cloud" {
        return Err("API Key is required for Mem0 Cloud mode.".to_string());
    }

    let client = reqwest::Client::new();
    let url = if mem0_type == "cloud" {
        format!("{}/v3/memories/add/", mem0_url.trim_end_matches('/'))
    } else {
        format!("{}/memories", mem0_url.trim_end_matches('/'))
    };

    let payload = json!({
        "user_id": user_id,
        "messages": [
            {
                "role": "user",
                "content": memory
            }
        ]
    });

    let mut req = client.post(&url).header("Content-Type", "application/json");
    req = apply_sidecar_auth(req, &mem0_type);
    if let Some(ref key) = api_key {
        if !key.is_empty() {
            req = req.header("Authorization", format!("Token {}", key));
        }
    }

    let response = req.json(&payload).send().await.map_err(|e| e.to_string())?;

    if !response.status().is_success() {
        let err_text = response.text().await.unwrap_or_default();
        return Err(format!("Mem0 API Error: {}", err_text));
    }

    // Mirror memory to Supabase DB and backup Chroma DB zip to Storage
    let user_id_clone = user_id.to_string();
    let memory_clone = memory.clone();
    tauri::async_runtime::spawn(async move {
        let _ = crate::storage::supabase::insert_memory_to_supabase(&user_id_clone, "semantic", &memory_clone).await;
        crate::storage::supabase::sync_all_to_cloud_async(None, None).await;
    });

    Ok(())
}
